jobs:
- job: Ubuntu_CMake
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      addToPath: true
  - script: |
      sudo apt update -q > /dev/null
      sudo apt install -yq --no-install-recommends gfortran liblapack-dev libblacs-mpi-dev libscalapack-mpi-dev libopenmpi-dev
    displayName: 'Install Linux prereqs'
  - script: |
      python -m pip install cmakeutils
      cmake_setup 3.15.0 --prefix $(HOME)/.local
      echo '##vso[task.prependpath]$(HOME)/.local/cmake-3.15.0-Linux-x86_64/bin'
    displayName: 'Install modern CMake'
  - script: |
      cmake -B $BUILD_DIR -S $SRC_DIR
      cmake --build $BUILD_DIR --parallel
    env:
      SRC_DIR: $(Build.SourcesDirectory)
      BUILD_DIR: $(Build.BinariesDirectory)
      FC: gfortran
    displayName: 'CMake: Configure and Build'
  - script: ctest --parallel --output-on-failure
    workingDirectory: $(Build.BinariesDirectory)
    displayName: 'CTest'

# - job: Ubuntu_Meson
  # pool:
    # vmImage: 'ubuntu-latest'

  # steps:
  # - task: UsePythonVersion@0
    # inputs:
      # versionSpec: '3.6'
      # addToPath: true
  # - script: |
      # sudo apt update -q
      # sudo apt install -yq --no-install-recommends gfortran liblapack-dev libblacs-mpi-dev libscalapack-mpi-dev libopenmpi-dev
    # displayName: 'Install Linux prereqs'
  # - script: |
      # python -m pip install meson
      # curl -Ls https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-linux.zip -o ninja-linux.zip
      # sudo unzip ninja-linux.zip -d /usr/local/bin/
    # displayName: 'setup Meson'
  # - script: |
      # meson setup $BUILD_DIR $SRC_DIR
      # meson test -C $BUILD_DIR
    # env:
      # SRC_DIR: $(Build.SourcesDirectory)
      # BUILD_DIR: $(Build.BinariesDirectory)
      # FC: gfortran
    # displayName: 'Build and test'
  # - publish: $(Build.BinariesDirectory)/meson-logs/testlog.txt
    # condition: succeededOrFailed()
    # artifact: TestLogUbuntuMeson

- job: MacOS_CMake
  pool:
    vmImage: macOS-10.14

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      addToPath: true
  - script: |
      brew install gcc lapack cmake open-mpi scalapack
    displayName: 'Install Prereqs'
  - script: |
      cmake --version
      cmake -B $BUILD_DIR -S $SRC_DIR
      cmake --build $BUILD_DIR --parallel
    env:
      SRC_DIR: $(Build.SourcesDirectory)
      BUILD_DIR: $(Build.BinariesDirectory)
      FC: gfortran
    displayName: 'CMake: Configure and Build'
  - script: ctest --parallel --output-on-failure
    workingDirectory: $(Build.BinariesDirectory)
    displayName: 'CTest'
