jobs:
- job: Ubuntu_CMake
  pool:
    vmImage: ubuntu-latest

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      addToPath: true
  - script: |
      sudo apt update -q > /dev/null
      sudo apt install -yq --no-install-recommends gfortran liblapack-dev libblacs-mpi-dev libscalapack-mpi-dev libopenmpi-dev
    displayName: 'Install Linux prereqs'
  - script: |
      python -m pip install cmakeutils
      cmake_setup 3.15.1 --prefix $(HOME)/.local
    displayName: 'install modern CMake'
  - script: |
      $(HOME)/.local/cmake-3.15.1-Linux-x86_64/bin/cmake -B build
      $(HOME)/.local/cmake-3.15.1-Linux-x86_64/bin/cmake --build build --parallel
    env:
      FC: gfortran
    displayName: 'CMake: Configure and Build'
  - script: $(HOME)/.local/cmake-3.15.1-Linux-x86_64/bin/ctest --parallel --output-on-failure
    workingDirectory: build
    displayName: 'CTest'

- job: Ubuntu_Meson
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      addToPath: true
  - script: |
      sudo apt update -q
      sudo apt install -yq --no-install-recommends gfortran liblapack-dev libblacs-mpi-dev libscalapack-mpi-dev libopenmpi-dev
    displayName: 'Install Linux prereqs'
  - script: |
      python -m pip install meson
      curl -Ls https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-linux.zip -o ninja-linux.zip
      sudo unzip ninja-linux.zip -d /usr/local/bin/
    displayName: 'install Meson'
  - script: meson setup build
    env:
      FC: gfortran
    displayName: 'Meson Configure and Generate'
  - script: meson test -C build
    displayName: 'Meson build and test'
  - publish: build/meson-logs/testlog.txt
    condition: succeededOrFailed()
    artifact: TestLog_Ubuntu_Meson

- job: MacOS_CMake
  pool:
    vmImage: macOS-latest

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      addToPath: true
  - script: brew install gcc lapack cmake open-mpi scalapack
    displayName: 'Install Prereqs'
  - script: cmake -B build
    env:
      FC: gfortran
    displayName: 'CMake configure and generate'
  - script: cmake --build build --parallel
    displayName: 'CMake build'
  - script: ctest --parallel --output-on-failure
    workingDirectory: build
    displayName: 'CTest'

- job: MacOS_Meson
  # need to figure out homebrew find scalapack on Mac--just try a physical Mac.
  condition: False
  pool:
    vmImage: macOS-latest

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      addToPath: true
  - script: |
      brew install gcc lapack ninja open-mpi scalapack
      python -m pip install meson
    displayName: 'Install Prereqs'
  - script: meson setup build
    env:
      FC: gfortran
    displayName: 'Meson Configure and Generate'
  - script: meson test -C build
    displayName: 'Meson build and test'
  - publish: build/meson-logs/testlog.txt
    condition: succeededOrFailed()
    artifact: TestLog_Mac_Meson
