name: ci

on: [push, pull_request]

jobs:

  linuxCmake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install CMake
      run: |
        python -m pip install cmakeutils
        cmake_setup ${cmake_version} --prefix ${HOME}/.local
      env:
        cmake_version: 3.15.3
    - name: Install packages
      run: sudo apt install -yq --no-install-recommends gfortran liblapack-dev libblacs-mpi-dev libscalapack-mpi-dev libopenmpi-dev openmpi-bin
    - name: CMake configure
      run: ${HOME}/.local/cmake-${cmake_version}-Linux-x86_64/bin/cmake -B build
      env:
        FC: gfortran
        cmake_version: 3.15.3
    - name: Cmake build
      run: ${HOME}/.local/cmake-${cmake_version}-Linux-x86_64/bin/cmake --build build --parallel
      env:
        cmake_version: 3.15.3
    - name: Ctest
      run: ${HOME}/.local/cmake-${cmake_version}-Linux-x86_64/bin/ctest -V
      env:
        cmake_version: 3.15.3


  linuxMeson:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install Meson
      run: |
        python -m pip install meson
        curl -Ls https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-linux.zip -o ninja-linux.zip
        sudo unzip ninja-linux.zip -d /usr/local/bin/
    - name: Install packages
      run: sudo apt install -yq --no-install-recommends gfortran liblapack-dev libblacs-mpi-dev libscalapack-mpi-dev libopenmpi-dev openmpi-bin
    - name: Meson configure
      run: meson setup build -Dsystem_blas=true
      env:
        FC: gfortran
    - name: Meson test
      run: meson test -C build

  macosMeson:
    needs: [linuxMeson]
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        brew install gcc ninja open-mpi
        python -m pip install meson
    - name: Meson configure
      run: meson setup build
      env:
        FC: gfortran
    - name: Meson test
      run: meson test -C build

  macosCmake:
    needs: [linuxCmake]
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: brew install gcc lapack cmake open-mpi scalapack
    - name: CMake configure
      run: cmake -B build
      env:
        FC: gfortran
    - name: CMake build
      run: cmake --build build --parallel
    - name: Ctest
      run: ctest -V
