name: ci_buildall

on:
  push:
    paths:
      - "**.cmake"
      - "**.txt"
      - ".github/workflows/ci_buildall.yml"
  pull_request:
  release:

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Install prereqs
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends gfortran libopenmpi-dev openmpi-bin

    - run: ctest -S setup.cmake -VV
      env:
        FC: gfortran
        CC: gcc
