name: ci_linux
env:
  cmake_version: '3.15.5'

on: [push, pull_request]

jobs:

  cmake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: pip install cmakeutils
    - run: cmake_setup ${cmake_version} --prefix ${HOME}/.local
    - name: Install prereqs
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends gfortran libopenmpi-dev openmpi-bin liblapack-dev libblacs-mpi-dev libscalapack-mpi-dev
    - run: ${HOME}/.local/cmake-${cmake_version}-Linux-x86_64/bin/cmake -B build
      env:
        FC: gfortran
    - run: ${HOME}/.local/cmake-${cmake_version}-Linux-x86_64/bin/cmake --build build --parallel
    - run: ${HOME}/.local/cmake-${cmake_version}-Linux-x86_64/bin/ctest -V
      working-directory: build

  meson:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: python -m pip install meson
    - name: Install prereqs
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends ninja-build gfortran libopenmpi-dev openmpi-bin liblapack-dev
    - run: meson setup build
      env:
        FC: gfortran
    - run: ninja -C build
    - run: meson test -C build -v
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Linux_Meson_Testlog
        path: build/meson-logs/testlog.txt
