name: ci_macos

on:
  push:
    paths:
      - "**.cmake"
      - "**.txt"
      - ".github/workflows/ci_macos.yml"
  pull_request:


jobs:

  cmake:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - run: brew install ninja lapack scalapack open-mpi

    - run: ctest -S setup.cmake -VV
      env:
        FC: gfortran-9
        CC: gcc-9
