name: ci_macos

on:
  push:
    paths:
      - "**.c"
      - "**.F"
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**.txt"
      - "**.build"
      - ".github/workflows/ci_macos.yml"
  pull_request:
    paths:
      - "**.c"
      - "**.F"
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**.txt"
      - "**.build"
      - ".github/workflows/ci_macos.yml"

jobs:

  meson:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - run: brew install gcc ninja open-mpi
    - run: pip install -r requirements.txt

    - run: meson setup build
      env:
        FC: gfortran-9
        CC: gcc-9
    - run: ninja -C build
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: MacPar_Meson_Buildlog
        path: build/meson-logs/meson-log.txt

    - run: meson test -C build -v
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: MacPar_Meson_Testlog
        path: build/meson-logs/testlog.txt

  cmake:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - run: brew install gcc open-mpi

    - run: cmake -B build
      env:
        FC: gfortran-9
        CC: gcc-9
    - run: cmake --build build --parallel
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: MacPar_Cmake_Buildlog
        path: build/CMakeFiles/CMakeError.log

    - run: ctest -V
      working-directory: build
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: MacPar_CMake_Testlog
        path: build/Testing/Temporary/LastTest.log

  cmakeSequential:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - run: brew install gcc lapack

    - run: cmake -B build -Dparallel=false
      env:
        FC: gfortran-9
        CC: gcc-9
    - run: cmake --build build --parallel
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: MacSeq_Cmake_Buildlog
        path: build/CMakeFiles/CMakeError.log

    - run: ctest -V
      working-directory: build
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: MacSeq_CMake_Testlog
        path: build/Testing/Temporary/LastTest.log
